services:
  ferricstore:
    image: ${FERRICSTORE_IMAGE:-ghcr.io/ferricstore/ferricstore:0.11.3@sha256:c2eef2036f45e7916359edfb92a50e3f36b8ea3c7a4067f22581305f5253c217}
    ports:
      - "6388:6388"
    environment:
      FERRICSTORE_PROTECTED_MODE: "false"
    volumes:
      - ferricstore_data:/data

volumes:
  ferricstore_data:
