services:
  ferricstore:
    image: ${FERRICSTORE_IMAGE:-quay.io/ferricstore/ferricstore:0.11.8@sha256:d472b337fcec536b46e4ba7549689bc5c7fc67948071f6e39cc13ca0e8879ce2}
    ports:
      - "6388:6388"
    environment:
      FERRICSTORE_PROTECTED_MODE: "false"
      FERRICSTORE_FLOW_SCHEDULER_ENABLED: "false"
    volumes:
      - ferricstore_data:/data

volumes:
  ferricstore_data:
