services:
  ferricstore:
    image: ${FERRICSTORE_IMAGE:-ghcr.io/ferricstore/ferricstore:0.10.1@sha256:198cffba8e2df2f5f66db9e6bbef83131f4841d4b90c65ee8091ac463ec6715d}
    ports:
      - "6388:6388"
    environment:
      FERRICSTORE_PROTECTED_MODE: "false"
    volumes:
      - ferricstore_data:/data

volumes:
  ferricstore_data:
